Reproducible Research Peer Assignment 1
=======================================
  
Loading and preprocessing the data
----------------------------------

Read in the file, then convert the date field into date format.

```{r}
data <- read.csv("activity.csv", stringsAsFactors = FALSE)
data$date <- as.Date(data$date, format = "%Y-%m-%d")
str(data)
```

What is mean total number of steps taken per day?
-------------------------------------------------

Calculate the total number of steps for each day, then plot the graph.

```{r}
total.steps.daily <- aggregate(steps ~ date, data = data, sum, na.rm = TRUE)
plot(total.steps.daily, type = "h", main = "Total number of steps taken each day", col = "magenta")
```

Now to calculate the mean and median total number of steps taken per day.  
Note: For days where all the data is NA, it will return NA for both mean and median.

```{r}
tapply(data$steps, data$date, summary)
```

What is the average daily activity pattern?
-------------------------------------------

Calculate the average number of steps by time interval, then plot the graph.

```{r}
total.steps.int <- tapply(data$steps, data$interval, mean, na.rm = TRUE)
plot(total.steps.int, type = "l", main = "Average number of steps by time interval", col = "magenta")
```

To find the 5-minute interval, on average across all the days in the dataset, that contains the maximum number of steps.

```{r}
total.steps.int[which.max(total.steps.int)]
```

Imputing missing values
-----------------------

